# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
source 'https://cdn.cocoapods.org/'

target 'DevApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Lynx', '3.2.0-rc.0', :subspecs => [
    'Framework',
  ]
  
  pod 'PrimJS', '2.11.1-rc.0', :subspecs => ['quickjs', 'napi']
  
  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.2.0-rc.0', :subspecs => [
    'Image',
    'Log',
    'Http',
  ]
  
  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end

target 'SDK' do
  use_frameworks!
  pod 'Lynx', '3.2.0-rc.0', :subspecs => [
    'Framework',
  ]
  
  pod 'PrimJS', '2.11.1-rc.0', :subspecs => ['quickjs', 'napi']
  
  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.2.0-rc.0', :subspecs => [
    'Image',
    'Log',
    'Http',
  ]
  
  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
  
end
