source 'https://cdn.cocoapods.org/'
platform :ios, '16.0'

target 'ReadyRemitLynxSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ReadyRemitLynxSDK
  pod 'Lynx', '3.2.0-rc.0', :subspecs => [
  'Framework',
  ]
  
  pod 'PrimJS', '2.11.1-rc.0', :subspecs => ['quickjs', 'napi']
  
  pod 'LynxService', '3.2.0-rc.0', :subspecs => [
  'Image',
  'Log',
  'Http',
  'Devtool',
  ]
  
  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
  
  pod 'LynxDevtool', '3.2.0-rc.0'
end
